### ISSUE TITLE
revanced tools error

### ISSUE THREAD

**Issue by pl1nk** [taku-nm/auto-cli#23] opened 2023-10-07 23:04 UTC
JDK integrity validated
Your ReVanced Tools are out of date or damaged... Re-downloading...
Expand-Archive : The path 'C:\Users\user\AppData\Local\revanced-cli\jdk.zip' either does not exist or is not a valid
file system path.
At line:1 char:1
+ Expand-Archive 'C:\Users\user\AppData\Local\revanced-cli\jdk.zip' -De ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (C:\Users\abod\A...ced-cli\jdk.zip:String) [Expand-Archive], InvalidOpe
   rationException
    + FullyQualifiedErrorId : ArchiveCmdletPathNotFound,Expand-Archive

Could Not Find C:\Users\user\AppData\Local\revanced-cli\jdk.zip

**Comment by taku-nm** [comment] 2023-10-08 00:08
Please add the following:
- Script version
- User directory name
- Screenshot of the entire terminal

**Comment by Cheesecake05067** [comment] 2023-10-08 03:01
Having the same issue using v2.1
![Capture](https://github.com/taku-nm/auto-cli/assets/122873788/3e5f39b3-cdee-4351-baf4-a1f0ea4cfdb6)

**Comment by taku-nm** [comment] 2023-10-08 03:19
I've reverted release 2.1; back to 2.0

**Comment by taku-nm** [comment] 2023-10-08 10:42
Can either of you contact me over the revanced discord to perform some rapid testing? 
I can't reproduce the problem and this looks like a bug with the batch interpreter again. But I could diagnose it fairly quickly if we could meet in VC

**Comment by Cheesecake05067** [comment] 2023-10-08 20:00
I could VC; my user is @yantoku

**Comment by taku-nm** [comment] 2023-10-08 21:06
issue resolved with re-release of 2.1;
osu found the issue with the conversions of carriage returns when processing it through git workflows, causing the script to not work properly on some machines

**Closed as completed by taku-nm** 2023-10-08 21:06 UTC
